// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://3vncw3c4f5cn5o26hno4a3qsai.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2wvltzgyknfp3i4zf7qrvuj62i"
};


export default awsmobile;
